//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25/9/2017 6:05:09 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace outGoModel
{
    public partial class Detalles {

        public Detalles()
        {
            OnCreated();
        }

        public virtual int IdFactura
        {
            get;
            set;
        }

        public virtual string TipoGasto
        {
            get;
            set;
        }

        public virtual double Monto
        {
            get;
            set;
        }

        public virtual Facturas Facturas
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Detalles toCompare = obj as Detalles;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdFactura, toCompare.IdFactura))
            return false;
          if (!Object.Equals(this.TipoGasto, toCompare.TipoGasto))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdFactura.GetHashCode();
          hashCode = (hashCode * 7) + TipoGasto.GetHashCode();
          return hashCode;
        }
        
        #endregion
    }

}
