//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25/9/2017 6:05:09 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace outGoModel
{
    public partial class Personas {

        public Personas()
        {
            this.Pagos = new List<Pagos>();
            this.Relaciones = new List<Relaciones>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Nombre
        {
            get;
            set;
        }

        public virtual string Email
        {
            get;
            set;
        }

        public virtual string Password
        {
            get;
            set;
        }

        public virtual IList<Pagos> Pagos
        {
            get;
            set;
        }

        public virtual IList<Relaciones> Relaciones
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
