//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25/9/2017 6:05:09 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace outGoModel
{
    public partial class Comercios {

        public Comercios()
        {
            this.Facturas = new List<Facturas>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Nombre
        {
            get;
            set;
        }

        public virtual string Ublicacion
        {
            get;
            set;
        }

        public virtual string Tipo
        {
            get;
            set;
        }

        public virtual IList<Facturas> Facturas
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
